import { auth, db, requireAdmin, isSuperAdmin, addAdmin, removeAdmin } from './auth.js';
import { collection, getDocs, doc, addDoc, updateDoc, deleteDoc, serverTimestamp, Timestamp } from 'https://www.gstatic.com/firebasejs/12.17.1/firebase-firestore.js';
import { onAuthStateChanged, signOut } from 'https://www.gstatic.com/firebasejs/12.17.1/firebase-auth.js';
let restaurants=[],currentUser=null;
const $=id=>document.getElementById(id); const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c])); const money=n=>`${Number(n||0).toLocaleString('ar-EG')} ج`; const dt=v=>v?.toDate?v.toDate():(v?new Date(v):null); const active=o=>o.active!==false&&(!dt(o.startAt)||new Date()>=dt(o.startAt))&&(!dt(o.endAt)||new Date()<=dt(o.endAt));
function message(t){const x=$('message');if(!x)return;x.textContent=t;x.style.display='block';clearTimeout(window.__m);window.__m=setTimeout(()=>x.style.display='none',3000)}
window.showPage=function(id,b){document.querySelectorAll('.page').forEach(x=>x.classList.remove('active'));$(id)?.classList.add('active');document.querySelectorAll('.menu button').forEach(x=>x.classList.remove('active'));b?.classList.add('active');$('pageTitle').textContent={dashboard:'لوحة المعلومات',restaurants:'المطاعم',products:'المنتجات',offers:'العروض',orders:'الطلبات',drivers:'الطيارين',customers:'العملاء',admins:'المشرفين'}[id]||'لوحة التحكم';({restaurants:loadRestaurants,products:loadProducts,offers:loadOffers,orders:loadOrders,drivers:loadDrivers,customers:loadCustomers,admins:loadAdmins}[id]||(()=>{}))()};
window.adminLogout=async()=>{await signOut(auth);location.replace('login.html')};
async function init(){if(!(await requireAdmin()))return;currentUser=auth.currentUser;if(!(await isSuperAdmin()))$('adminsMenu').style.display='none';$('firebaseStatus').textContent='Firebase متصل ✅';await loadRestaurants();await loadDashboard();await loadOffers()}
async function loadDashboard(){try{const [o,c,r,d,f]=await Promise.all([getDocs(collection(db,'orders')),getDocs(collection(db,'customers')),getDocs(collection(db,'restaurants')),getDocs(collection(db,'drivers')),getDocs(collection(db,'offers'))]);$('statOrders').textContent=o.size;$('statCustomers').textContent=c.size;$('statRestaurants').textContent=r.size;$('statDrivers').textContent=d.size;$('statOffers').textContent=f.docs.filter(x=>active(x.data())).length;let s=0;o.forEach(x=>s+=Number(x.data()?.total||x.data()?.totalPrice||0));$('statSales').textContent=money(s);const a=o.docs.map(x=>({id:x.id,...x.data()})).sort((x,y)=>(dt(y.createdAt)?.getTime()||0)-(dt(x.createdAt)?.getTime()||0)).slice(0,8);$('recentOrders').innerHTML=a.length?a.map(x=>`<div class="item"><div class="item-info"><strong>#${esc(x.id)}</strong><small>${esc(x.customerName||x.customerEmail||x.customerId||'عميل')} — ${money(x.total||x.totalPrice)}</small></div><span class="badge">${esc(x.status||'جديد')}</span></div>`).join(''):'لا توجد طلبات.'}catch(e){console.error(e);message('تعذر تحميل لوحة المعلومات ❌')}}
window.addRestaurant=async()=>{const n=$('restaurantName').value.trim();if(!n)return message('اكتب اسم المطعم ❌');try{await addDoc(collection(db,'restaurants'),{name:n,category:$('restaurantCategory').value.trim(),rating:Number($('restaurantRating').value||0),deliveryFee:Number($('restaurantDelivery').value||0),image:$('restaurantImage').value.trim(),description:$('restaurantDescription').value.trim(),latitude:Number($('restaurantLatitude').value||0),longitude:Number($('restaurantLongitude').value||0),active:true,createdAt:serverTimestamp()});document.querySelectorAll('#restaurants input').forEach(x=>x.value='');message('تم إضافة المطعم ✅');await loadRestaurants();await loadDashboard()}catch(e){console.error(e);message('تعذر إضافة المطعم ❌')}};
async function loadRestaurants(){try{const s=await getDocs(collection(db,'restaurants'));restaurants=s.docs.map(d=>({id:d.id,...d.data()}));$('productRestaurant').innerHTML='<option value="">اختر المطعم</option>'+restaurants.map(r=>`<option value="${esc(r.id)}">${esc(r.name)}</option>`).join('');$('offerRestaurant').innerHTML='<option value="">عرض عام</option>'+restaurants.map(r=>`<option value="${esc(r.id)}">${esc(r.name)}</option>`).join('');$('restaurantsList').innerHTML=restaurants.length?restaurants.map(r=>`<div class="item"><div class="item-info"><strong>${esc(r.name)}</strong><small>${esc(r.category||'')} — توصيل ${money(r.deliveryFee)}</small></div><div class="actions"><button class="secondary" onclick="showRestaurantOffers('${r.id}')">🎁 عروض المطعم</button><button class="danger" onclick="deleteRestaurant('${r.id}')">حذف</button></div></div>`).join(''):'لا توجد مطاعم.'}catch(e){console.error(e);message('تعذر تحميل المطاعم ❌')}}
window.deleteRestaurant=async id=>{if(!confirm('حذف المطعم؟'))return;try{await deleteDoc(doc(db,'restaurants',id));message('تم حذف المطعم');await loadRestaurants();await loadDashboard()}catch(e){console.error(e);message('تعذر الحذف ❌')}};
window.showRestaurantOffers=async id=>{showPage('offers',document.querySelector("button[onclick*='offers']"));$('offerRestaurant').value=id;await loadOffers(id)};
window.addProduct=async()=>{const rid=$('productRestaurant').value,n=$('productName').value.trim(),p=Number($('productPrice').value);if(!rid||!n||!Number.isFinite(p)||p<0)return message('أكمل بيانات المنتج ❌');try{await addDoc(collection(db,'restaurants',rid,'products'),{name:n,price:p,image:$('productImage').value.trim(),description:$('productDescription').value.trim(),active:true,createdAt:serverTimestamp()});$('productName').value=$('productPrice').value=$('productImage').value=$('productDescription').value='';message('تم إضافة المنتج ✅');await loadProducts()}catch(e){console.error(e);message('تعذر إضافة المنتج ❌')}};
async function loadProducts(){const l=$('productsList');try{let a=[];for(const r of restaurants){const s=await getDocs(collection(db,'restaurants',r.id,'products'));s.forEach(d=>a.push({id:d.id,restaurantId:r.id,restaurantName:r.name,...d.data()}))}l.innerHTML=a.length?a.map(p=>`<div class="item"><div class="item-info"><strong>${esc(p.name)}</strong><small>${esc(p.restaurantName)} — ${money(p.price)}</small></div><button class="danger" onclick="deleteProduct('${p.restaurantId}','${p.id}')">حذف</button></div>`).join(''):'لا توجد منتجات.'}catch(e){console.error(e);l.textContent='تعذر تحميل المنتجات ❌'}}
window.deleteProduct=async(r,p)=>{if(!confirm('حذف المنتج؟'))return;try{await deleteDoc(doc(db,'restaurants',r,'products',p));message('تم حذف المنتج');await loadProducts()}catch(e){console.error(e);message('تعذر الحذف ❌')}};
window.addOffer=async()=>{const t=$('offerTitle').value.trim(),p=Number($('offerPrice').value),op=Number($('offerOldPrice').value||0);if(!t||!Number.isFinite(p)||p<0)return message('أكمل بيانات العرض ❌');try{await addDoc(collection(db,'offers'),{title:t,description:$('offerDescription').value.trim(),image:$('offerImage').value.trim(),oldPrice:op,price:p,discount:op>0?Math.max(0,Math.round((1-p/op)*100)):0,restaurantId:$('offerRestaurant').value||null,showOnHome:$('offerShowHome').checked,active:true,startAt:$('offerStart').value?Timestamp.fromDate(new Date($('offerStart').value)):null,endAt:$('offerEnd').value?Timestamp.fromDate(new Date($('offerEnd').value)):null,createdAt:serverTimestamp(),createdBy:currentUser?.uid||null});$('offerTitle').value=$('offerDescription').value=$('offerImage').value=$('offerStart').value=$('offerEnd').value='';message('تم إضافة العرض ✅');await loadOffers();await loadDashboard()}catch(e){console.error(e);message('تعذر إضافة العرض ❌')}};
async function loadOffers(filter=null){const l=$('offersList');if(!l)return;try{const s=await getDocs(collection(db,'offers'));const a=s.docs.map(d=>({id:d.id,...d.data()})).filter(x=>!filter||x.restaurantId===filter);l.innerHTML=a.length?a.map(o=>{const r=restaurants.find(x=>x.id===o.restaurantId);return `<div class="item"><div class="item-info"><strong>${esc(o.title)}</strong><small>${esc(r?.name||'عرض عام')} — ${money(o.price)} ${o.oldPrice?`بدل ${money(o.oldPrice)}`:''} — خصم ${Number(o.discount||0)}%</small><small>${o.showOnHome?'يظهر في الرئيسية':'ليس في الرئيسية'} — ${active(o)?'نشط':'غير نشط'}</small></div><div class="actions"><button class="secondary" onclick="toggleOffer('${o.id}',${o.active!==false})">${o.active===false?'تفعيل':'إيقاف'}</button><button class="danger" onclick="deleteOffer('${o.id}')">حذف</button></div></div>`}).join(''):'لا توجد عروض.'}catch(e){console.error(e);message('تعذر تحميل العروض ❌')}}
window.toggleOffer=async(id,state)=>{try{await updateDoc(doc(db,'offers',id),{active:!state,updatedAt:serverTimestamp()});await loadOffers();await loadDashboard()}catch(e){console.error(e);message('تعذر تعديل العرض ❌')}};window.deleteOffer=async id=>{if(!confirm('حذف العرض؟'))return;try{await deleteDoc(doc(db,'offers',id));message('تم حذف العرض');await loadOffers();await loadDashboard()}catch(e){console.error(e);message('تعذر الحذف ❌')}};
async function loadOrders(){const b=$('ordersTable');try{const s=await getDocs(collection(db,'orders'));const a=s.docs.map(d=>({id:d.id,...d.data()})).sort((x,y)=>(dt(y.createdAt)?.getTime()||0)-(dt(x.createdAt)?.getTime()||0));b.innerHTML=a.length?a.map(o=>`<tr><td>#${esc(o.id)}</td><td>${esc(o.customerName||o.customerEmail||o.customerId||'—')}</td><td>${money(o.total||o.totalPrice)}</td><td>${esc(o.status||'جديد')}</td><td><select onchange="changeOrderStatus('${o.id}',this.value)"><option value="">الحالة</option><option>جديد</option><option>قيد التنفيذ</option><option>في الطريق</option><option>مكتمل</option><option>ملغي</option></select></td></tr>`).join(''):'<tr><td colspan="5">لا توجد طلبات</td></tr>'}catch(e){console.error(e);b.innerHTML='<tr><td colspan="5">تعذر تحميل الطلبات</td></tr>'}};
window.changeOrderStatus=async(id,s)=>{if(!s)return;try{await updateDoc(doc(db,'orders',id),{status:s,updatedAt:serverTimestamp()});message('تم تحديث حالة الطلب ✅');await loadOrders();await loadDashboard()}catch(e){console.error(e);message('تعذر تحديث الطلب ❌')}};
async function loadCustomers(){try{const s=await getDocs(collection(db,'customers'));$('customersList').innerHTML=s.size?[...s.docs].map(d=>{const x=d.data();return `<div class="item"><div class="item-info"><strong>${esc(x.name||x.email||d.id)}</strong><small>${esc(x.email||'')} — ${esc(x.phone||'')}</small></div></div>`}).join(''):'لا يوجد عملاء.'}catch(e){console.error(e);$('customersList').textContent='تعذر تحميل العملاء ❌'}}
async function loadDrivers(){try{const s=await getDocs(collection(db,'drivers'));$('driversList').innerHTML=s.size?[...s.docs].map(d=>{const x=d.data();return `<div class="item"><div class="item-info"><strong>${esc(x.name||x.email||d.id)}</strong><small>${esc(x.phone||'')} — ${esc(x.status||'متاح')}</small></div></div>`}).join(''):'لا يوجد طيارون مسجلون بعد.'}catch(e){console.error(e);$('driversList').textContent='تعذر تحميل الطيارين ❌'}}
async function loadAdmins(){if(!(await isSuperAdmin()))return;try{const s=await getDocs(collection(db,'roles'));const a=s.docs.map(d=>({id:d.id,...d.data()})).filter(x=>x.role==='admin'||x.role==='superadmin');$('adminsList').innerHTML=a.map(x=>`<div class="item"><div class="item-info"><strong>👑 ${esc(x.email||x.id)}</strong><small>${x.role==='superadmin'?'Super Admin':'Admin'}</small></div>${x.role==='admin'?`<button class="danger" onclick="demoteAdmin('${x.id}','${esc(x.email||'')}')">إزالة</button>`:''}</div>`).join('')||'لا يوجد مشرفون.'}catch(e){console.error(e);message('تعذر تحميل المشرفين ❌')}}
window.promoteAdmin=async()=>{const u=$('adminUid').value.trim(),e=$('adminEmail').value.trim();if(!u||!e)return message('أدخل UID والإيميل ❌');try{await addAdmin(u,e);$('adminUid').value='';$('adminEmail').value='';message('تمت إضافة المشرف ✅');await loadAdmins()}catch(x){console.error(x);message('تعذر إضافة المشرف ❌')}};window.demoteAdmin=async(u,e)=>{if(!confirm('إزالة صلاحية الأدمن؟'))return;try{await removeAdmin(u,e);message('تمت إزالة الصلاحية ✅');await loadAdmins()}catch(x){console.error(x);message('تعذر إزالة الصلاحية ❌')}};
onAuthStateChanged(auth,u=>{if(u)init()});
