/* Restaurants page: restaurant -> products -> embedded cart */
(async function(){
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const money=n=>Number(n||0).toLocaleString('ar-EG')+' ج';
  const wait=()=>new Promise(resolve=>{if(window.firebaseReady)return resolve(true);let n=0;const t=setInterval(()=>{if(window.firebaseReady){clearInterval(t);resolve(true)}else if(++n>60){clearInterval(t);resolve(false)}},100)});
  if(!(await wait())){document.getElementById('restaurantsContainer').innerHTML='<div class="restaurants-message">❌ تعذر الاتصال بقاعدة البيانات</div>';return}
  const db=window.firebaseDB, col=window.firebaseCollection, getDocs=(await import('https://www.gstatic.com/firebasejs/12.17.1/firebase-firestore.js')).getDocs;
  let restaurants=[];
  try{const s=await getDocs(col(db,'restaurants'));restaurants=s.docs.map(d=>({id:d.id,...d.data()})).filter(r=>r.active!==false)}catch(e){console.error(e);document.getElementById('restaurantsContainer').innerHTML='<div class="restaurants-message">❌ تعذر تحميل المطاعم</div>';return}
  const container=document.getElementById('restaurantsContainer');
  container.innerHTML=`<div class="restaurant-picker" id="restaurantPicker">${restaurants.map(r=>`<button type="button" class="restaurant-choice" data-id="${esc(r.id)}"><img src="${esc(r.image||'assets/logo.png')}"><div><strong>${esc(r.name)}</strong><small>${esc(r.category||'مطعم')} ${r.rating?`★ ${esc(r.rating)}`:''}</small></div></button>`).join('')||'<div class="restaurants-message">لا توجد مطاعم متاحة حالياً.</div>'}</div><div id="selectedRestaurantArea"></div><section id="restaurantCart" class="restaurant-cart"></section>`;
  async function selectRestaurant(id,scroll=true){const r=restaurants.find(x=>x.id===id);if(!r)return;window.__selectedRestaurant=r;document.querySelectorAll('.restaurant-choice').forEach(b=>b.classList.toggle('selected',b.dataset.id===id));const area=document.getElementById('selectedRestaurantArea');area.innerHTML=`<div class="selected-restaurant"><div class="selected-head"><div><h2>🍔 ${esc(r.name)}</h2><p>${esc(r.description||'اختر منتجاتك من المطعم')}</p></div><button class="primary" onclick="document.getElementById('restaurantCart').scrollIntoView({behavior:'smooth'})">🛒 السلة <span id="cartCountLocal">0</span></button></div><div id="productsArea" class="products-grid">⏳ جاري تحميل المنتجات...</div></div>`;try{const s=await getDocs(col(db,'restaurants',r.id,'products'));const products=s.docs.map(d=>({id:d.id,...d.data()})).filter(p=>p.active!==false);document.getElementById('productsArea').innerHTML=products.length?products.map(p=>`<article class="restaurant-product"><img src="${esc(p.image||'assets/logo.png')}" alt="${esc(p.name)}"><div class="product-body"><h3>${esc(p.name)}</h3><p>${esc(p.description||'')}</p><strong>${money(p.price)}</strong><button class="primary" type="button" data-add="${esc(p.id)}">➕ إضافة للسلة</button></div></article>`).join(''):'<div class="restaurants-message">لا توجد منتجات لهذا المطعم بعد.</div>';document.querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>{const p=products.find(x=>x.id===b.dataset.add);window.addToCart(p,r);updateLocalCount()})}catch(e){console.error(e);document.getElementById('productsArea').innerHTML='<div class="restaurants-message">❌ تعذر تحميل المنتجات</div>'}updateLocalCount();if(scroll)area.scrollIntoView({behavior:'smooth',block:'start'});window.renderMandoubCart?.()}
  function updateLocalCount(){const e=document.getElementById('cartCountLocal');if(e)e.textContent=(window.getMandoubCart?.()||[]).reduce((s,x)=>s+x.quantity,0)}
  function bind(){document.querySelectorAll('.restaurant-choice').forEach(b=>b.onclick=()=>selectRestaurant(b.dataset.id));const params=new URLSearchParams(location.search),hash=location.hash;const saved=(window.getMandoubCart?.()||[])[0]?.restaurantId;const first=params.get('restaurant')||saved||restaurants[0]?.id;if(first)selectRestaurant(first,false);if(hash==='#cart')setTimeout(()=>window.openCart?.(),300)}
  bind();
  document.addEventListener('DOMContentLoaded',()=>setTimeout(bind,0));
  window.addEventListener('mandoubCartChanged',updateLocalCount);
})();
