/* MANDOUB - Talabat style restaurant listing */
import{auth,db as userDb}from'./auth.js';
import{getDoc,doc,setDoc,serverTimestamp}from'https://www.gstatic.com/firebasejs/12.17.1/firebase-firestore.js';
(async function(){
const esc=v=>String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
const wait=()=>new Promise(resolve=>{if(window.firebaseReady)return resolve(true);let n=0;const t=setInterval(()=>{if(window.firebaseReady){clearInterval(t);resolve(true)}else if(++n>60){clearInterval(t);resolve(false)}},100)});
if(!(await wait()))return;
const db=window.firebaseDB,col=window.firebaseCollection;
const{getDocs}=await import('https://www.gstatic.com/firebasejs/12.17.1/firebase-firestore.js');
let restaurants=[],favorites=[],offers=[];
async function loadFav(){const u=auth.currentUser;if(!u){try{favorites=JSON.parse(localStorage.getItem('mandoub_fav_restaurants')||'[]')}catch{favorites=[]}return}try{const s=await getDoc(doc(userDb,'customers',u.uid));favorites=s.exists()?(s.data().favoriteRestaurants||[]):[]}catch{favorites=[]}}
async function toggleFav(id){const u=auth.currentUser;const a=new Set(favorites);a.has(id)?a.delete(id):a.add(id);favorites=[...a];if(!u){localStorage.setItem('mandoub_fav_restaurants',JSON.stringify(favorites));render();return}try{await setDoc(doc(userDb,'customers',u.uid),{favoriteRestaurants:favorites,updatedAt:serverTimestamp()},{merge:true});render()}catch(e){console.error(e)}}
window.toggleRestaurantFavorite=toggleFav;
function activeOffer(o){if(o.active===false)return false;const now=Date.now(),s=o.startAt?.toDate?o.startAt.toDate().getTime():o.startAt?new Date(o.startAt).getTime():0,e=o.endAt?.toDate?o.endAt.toDate().getTime():o.endAt?new Date(o.endAt).getTime():0;return(!s||now>=s)&&(!e||now<=e)}
try{const s=await getDocs(col(db,'restaurants'));restaurants=s.docs.map(d=>({id:d.id,...d.data()})).filter(r=>r.active!==false)}catch(e){console.error(e);document.getElementById('restaurantsContainer').innerHTML='<div class="restaurants-message">❌ تعذر تحميل المطاعم</div>';return}
try{const s=await getDocs(col(db,'offers'));offers=s.docs.map(d=>({id:d.id,...d.data()})).filter(activeOffer)}catch(e){console.warn('offers',e);offers=[]}
await loadFav();
const container=document.getElementById('restaurantsContainer'),search=document.getElementById('search'),typeFilters=document.querySelectorAll('#typeFilters .pill'),foodFilters=document.getElementById('foodFilters');
const food=[...new Set(restaurants.map(r=>r.foodCategory||r.category).filter(Boolean))];
foodFilters.innerHTML='<button class="pill active" data-food="all">كل أنواع الأكل</button>'+food.map(x=>`<button class="pill" data-food="${esc(x)}">${esc(x)}</button>`).join('');
let type=new URLSearchParams(location.search).get('type')||'all',foodType='all';
function setActive(){typeFilters.forEach(b=>b.classList.toggle('active',b.dataset.type===type));foodFilters.querySelectorAll('.pill').forEach(b=>b.classList.toggle('active',b.dataset.food===foodType))}
function offerFor(r){return offers.find(o=>o.restaurantId===r.id)||offers.find(o=>!o.restaurantId&&o.showOnHome)}
function render(){
const q=(search?.value||'').trim().toLowerCase();
const list=restaurants.filter(r=>(type==='all'||(r.businessType||'restaurant')===type)&&(foodType==='all'||(r.foodCategory||r.category||'')===foodType)&&(!q||`${r.name||''} ${r.category||''} ${r.foodCategory||''}`.toLowerCase().includes(q)));
container.innerHTML=`<div class="restaurant-list">${list.map(r=>{const o=offerFor(r);const delivery=window.getMandoubDelivery?.(r);const deliveryText=delivery?.fee===-1?`🚫 خارج نطاق التوصيل`:delivery?.fee!=null?`🚚 ${delivery.fee} ج • ${Number(delivery.distance||0).toFixed(1)} كم`:'🚚 حدد موقعك للتوصيل';return `<article class="talabat-rest"><button class="rest-fav ${favorites.includes(r.id)?'active':''}" onclick="toggleRestaurantFavorite('${esc(r.id)}')">${favorites.includes(r.id)?'♥':'♡'}</button><a href="restaurant-menu.html?id=${encodeURIComponent(r.id)}"><img class="rest-photo" src="${esc(r.image||'assets/logo.png')}" onerror="this.onerror=null;this.src='assets/logo.png'" alt="${esc(r.name)}"><div class="rest-data"><strong class="rest-name">${esc(r.name||'مطعم')}</strong><div class="rest-meta"><span class="star">★</span> ${esc(r.rating||'—')} ${r.deliveryTime?` • ${esc(r.deliveryTime)} دقيقة`:''} ${r.deliveryFee!=null?` • ${esc(r.deliveryFee)} ج.م`:''}</div><div class="rest-delivery">${deliveryText}</div>${o?`<span class="rest-offer">${esc(o.discount?`خصم ${o.discount}% على منتجات مختارة`:o.title||'عرض متاح')}</span>`:''}</div><span class="rest-arrow">‹</span></a></article>`}).join('')||'<div class="restaurants-message">لا توجد نتائج مطابقة حاليًا.</div>'}</div>`;
}
typeFilters.forEach(b=>b.onclick=()=>{type=b.dataset.type;setActive();render()});
foodFilters.addEventListener('click',e=>{const b=e.target.closest('.pill');if(!b)return;foodType=b.dataset.food;setActive();render()});
search?.addEventListener('input',render);setActive();render();
window.addEventListener('mandoubLocationChanged',render);window.addEventListener('mandoubCartChanged',render);
try{const{onAuthStateChanged}=await import('https://www.gstatic.com/firebasejs/12.17.1/firebase-auth.js');onAuthStateChanged(auth,async()=>{await loadFav();render()})}catch{}
const ui=document.createElement('style');ui.id='mandoubRestaurantsMobileUI';ui.textContent=`html,body{width:100%;max-width:100%;overflow-x:hidden!important}.navbar{width:100%!important;min-height:64px!important;padding:8px 10px!important;display:flex!important;align-items:center!important;gap:8px!important;position:sticky!important;top:0!important;z-index:100!important}.navbar .brand img{width:42px!important;height:42px!important}.navbar nav{display:flex!important;flex:1!important;gap:4px!important;overflow-x:auto!important;scrollbar-width:none!important}.navbar nav::-webkit-scrollbar{display:none}.navbar nav a{flex:0 0 auto!important;font-size:12px!important;padding:8px 9px!important}.nav-actions{display:flex!important;gap:5px!important}.nav-actions .login{font-size:11px!important;padding:8px 9px!important}.nav-actions .cart{font-size:17px!important;padding:7px!important}.rest-page{width:100%!important;max-width:720px!important;padding:10px 9px 105px!important}.rest-head{margin:6px 2px 10px!important}.rest-head h1{font-size:22px!important}.rest-search{height:46px!important}.location-box{width:100%!important;overflow:hidden!important}.restaurant-list{gap:9px!important}.talabat-rest{min-height:112px!important;border-radius:18px!important;padding:8px!important}.rest-photo{width:96px!important;height:96px!important;flex-basis:96px!important;border-radius:15px!important}.rest-data{gap:4px!important}.rest-name{font-size:17px!important}.rest-meta{font-size:12px!important}.rest-delivery{font-size:11px!important}.rest-offer{font-size:11px!important;padding:3px 6px!important}.rest-fav{width:33px!important;height:33px!important;top:8px!important;left:8px!important}.rest-arrow{font-size:18px!important}@media(max-width:380px){.navbar nav a:nth-child(4){display:none!important}.rest-photo{width:88px!important;height:88px!important;flex-basis:88px!important}.rest-name{font-size:16px!important}}`;document.head.appendChild(ui);
})();